[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/multistep"

[[constraint]]
  branch = "master"
  name = "github.com/pearkes/goconfig"
[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"
